GNU nano 7.2                                                                                                    configmap.yaml                                                                                                             apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  spring.datasource.url: jdbc:mysql://mysql-service:3306/ERP_DataBase
  spring.datasource.username: root
  spring.jpa.show-sql: "true"
  spring.jpa.hibernate.ddl-auto: update
  server.port: "8080"
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include: "*"
  management.endpoint.health.enabled: "true"
  management.endpoint.info.enabled: "true"
  management.endpoint.metrics.enabled: "true"
  management.endpoint.env.enabled: "true"
  management.endpoint.beans.enabled: "true"
  management.metrics.export.prometheus.enabled: "true"
  server.servlet.context-path: /api/v1
  jwt.secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
  jwt.expiration: "6000000"
  spring.mvc.throw-exception-if-no-handler-found: "true"
  spring.web.resources.add-mappings: "false"
  spring.servlet.multipart.enabled: "true"
  spring.servlet.multipart.max-file-size: 10MB
  spring.servlet.multipart.max-request-size: 10MB
  spring.thymeleaf.prefix: classpath:/templates/
  spring.thymeleaf.suffix: .html
  resilience4j.circuitbreaker.configs.default.slidingWindowSize: "100"
  resilience4j.circuitbreaker.configs.default.failureRateThreshold: "50"
  resilience4j.circuitbreaker.configs.default.waitDurationInOpenState: "10000"
  resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState: "10"
  resilience4j.circuitbreaker.configs.default.slidingWindowType: COUNT_BASED
  resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls: "10"
  resilience4j.circuitbreaker.configs.default.waitDurationInHalfOpenState: "5000"
  resilience4j.circuitbreaker.instances.rabbitmqService.baseConfig: default
