#name: Build, Test, and Deploy
#
#on:
#  push:
#    tags:
#      - 'v*'  # Trigger workflow only on version tags (e.g., v1.0.0)
#  workflow_dispatch: # Also allows manual triggering
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      - name: Set Version
#        id: set_version
#        run: |
#          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
#            VERSION="${GITHUB_REF##*/}"
#          else
#            VERSION="latest"  # Use latest if not a tag
#          fi
#          echo "VERSION=${VERSION}" >> $GITHUB_ENV
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#
#      - name: Verify JAR File
#        run: ls -l target/
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Install Docker Compose
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y docker-compose
#      # Step to get the tag version
#      - name: Get Tag Version
#        id: get_version
#        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
#
#      # Docker Hub login
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and Tag Docker Image
#        run: |
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/erp:${{ env.VERSION }} .
#          docker tag ${{ secrets.DOCKER_USERNAME }}/erp:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/erp:latest
#      - name: Push Docker Image to Docker Hub
#        run: |
#          docker push ${{ secrets.DOCKER_USERNAME }}/erp:${{ env.VERSION }}
#          docker push ${{ secrets.DOCKER_USERNAME }}/erp:latest
#  test:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Run Tests
#        run: mvn test --file pom.xml
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: [build, test]
#    environment:
#      name: 'Production'
#
#    steps:
#      - name: SSH Commands to Deploy
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.AZURE_VM_HOST }}
#          username: ${{ secrets.AZURE_VM_USERNAME }}
#          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
#          script: |
#            cd ~ || exit
#            printf "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin || exit
#            docker pull ${{ secrets.DOCKER_USERNAME }}/erp:latest || exit
#            docker-compose -f docker-compose.light.yml up -d || exit
